### ISSUE TITLE
Display exact VP spent when selecting slider value / DTC return

### ISSUE THREAD

**Issue by d00k13dotcom** [oneloveipfs/ipfsVideoUploader#51]
When posting there is no clearly defined amount of VP being spent currently only a %. This makes it a bit of a guessing game unless you happen to watch or know how fast you charge. Having the display of "VP# of wholeVP#" while also allowing slider selection showing % will greatly help for any potential excess VP burning.

To add to this could there not also be the current estimated DTC payout from given VP?

**Comment by techcoderx** [comment]
payouts are difficult to estimate due to the nature of the reward pool
