### ISSUE TITLE
Improvements to purchase page

### ISSUE THREAD

**Issue by tangodev** [oneloveipfs/ipfsVideoUploader#53]
The purchase page seems OK, but needs slightly more love :wink: 

I suggest making the items on the left **bold** and perhaps aligning the elements on the right.

![image](https://user-images.githubusercontent.com/12778629/112555115-d5ce2f80-8dc7-11eb-8b00-91d9ca3d6c10.png)

Also: the contents of the memo `to: dtc@user` could benefit from the "COPY" icon.

I click and see:

> The memo is now copied to your clipboard.

**Comment by tangodev** [comment]
Consider also:

![image](https://user-images.githubusercontent.com/12778629/112555460-84727000-8dc8-11eb-8835-66cc1ecb3962.png)

"Pay on DTube - a new window will open"

**Comment by techcoderx** [comment]
the real issue here is the lack of a proper wallet frontend, not the lack of instructions shown. Avalon needs a browser extension at least so that there is no need to enter private keys into websites, and only two clicks is needed to create the payment request and confirm.
