### ISSUE TITLE
[UX] [appimage] Add a customized appimage icon (when displayed on taskbar) (super low priority, eye candy)

### ISSUE THREAD

**Issue by tangodev** [oneloveipfs/ipfsVideoUploader#56]
Currently Plasma Desktop (KDE) shows the standard placeholder "X" for X programs.

Taskbar
![image](https://user-images.githubusercontent.com/12778629/112760108-26c36b00-8ff6-11eb-801a-3894533f9290.png)

Window icon
![image](https://user-images.githubusercontent.com/12778629/112760141-478bc080-8ff6-11eb-887a-92e40c468cf4.png)

Consider adding the IPFS OneLove icon here instead.

**Comment by techcoderx** [comment]
App icons on linux builds are inconsistent, the icons do show up on PopOS. Might be more of the Electron framework issue.
